/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Empty: typeof import('./src/components/Empty.vue')['default']
    FaSolidDice: typeof import('~icons/fa-solid/dice')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    NotoV1Bread: typeof import('~icons/noto-v1/bread')['default']
    NotoV1CurryRice: typeof import('~icons/noto-v1/curry-rice')['default']
    NotoV1Hamburger: typeof import('~icons/noto-v1/hamburger')['default']
    NotoV1Popcorn: typeof import('~icons/noto-v1/popcorn')['default']
    NotoV1ShallowPanOfFood: typeof import('~icons/noto-v1/shallow-pan-of-food')['default']
    NotoV1Shortcake: typeof import('~icons/noto-v1/shortcake')['default']
    NotoV1TeacupWithoutHandle: typeof import('~icons/noto-v1/teacup-without-handle')['default']
    PhArrowFatDown: typeof import('~icons/ph/arrow-fat-down')['default']
    PhPlayBold: typeof import('~icons/ph/play-bold')['default']
    PlanCard: typeof import('./src/components/PlanCard.vue')['default']
    PlanCardCtrl: typeof import('./src/components/PlanCardCtrl.vue')['default']
    PlanEditor: typeof import('./src/components/PlanEditor.vue')['default']
    PlanViewer: typeof import('./src/components/PlanViewer.vue')['default']
    Roller: typeof import('./src/components/Roller.vue')['default']
    UilAngleDown: typeof import('~icons/uil/angle-down')['default']
    UilCheck: typeof import('~icons/uil/check')['default']
    UilEditAlt: typeof import('~icons/uil/edit-alt')['default']
    UilGithubAlt: typeof import('~icons/uil/github-alt')['default']
    UilSetting: typeof import('~icons/uil/setting')['default']
    UilSpinner: typeof import('~icons/uil/spinner')['default']
    UilTimes: typeof import('~icons/uil/times')['default']
    UilTrashAlt: typeof import('~icons/uil/trash-alt')['default']
  }
}
